services:
  liloidc:
    build: .
    ports:
      - "${PORT:-9876}:${PORT:-9876}"
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./clients.json:/app/clients.json:ro
      - ./users.json:/app/users.json:ro
